import { test, expect } from '@playwright/test';

const num = 21;

test('test', async ({ page }) => {
  await page.goto('https://staging.bigapplegreeters.net/visitor/register');
  await page.locator('#first_name').click();
  await page.locator('#first_name').fill('Fake' + num);
  await page.locator('#last_name').click();
  await page.locator('#last_name').fill('Visitor' + num);
  await page.locator('#email').click();
  await page.locator('#email').fill('BigAppleTesting2312+visitor'+ num +'@gmail.com');
  await page.locator('#email_confirmation').click();
  await page.locator('#email_confirmation').fill('BigAppleTesting2312+visitor'+ num + '@gmail.com');
  await page.locator('#address_1').click();
  await page.locator('#address_1').fill('Fake Address Line 1');
  await page.locator('#address_2').click();
  await page.locator('#address_2').fill('Fake Address Line 2');
  await page.locator('#city').click();
  await page.locator('#city').fill('Fake City');
  await page.locator('#state_province').click();  
  await page.locator('#state_province').fill('Fake State');
  await page.locator('#postal_code').click();
  await page.locator('#postal_code').fill('Fake Zip');
  await page.getByText('Country * -').click();
  await page.locator('#country').selectOption('United States');
  await page.getByRole('textbox', { name: 'Phone 1' }).click();
  await page.getByRole('textbox', { name: 'Phone 1' }).fill('1');
  await page.locator('select[name="phone_1_type"]').selectOption('home');
  await page.getByPlaceholder('Phone 2').click();
  await page.getByPlaceholder('Phone 2').fill('2');
  await page.locator('select[name="phone_2_type"]').selectOption('work');
  await page.locator('#whatsapp_number').click();
  await page.locator('#whatsapp_number').fill('3');
  await page.getByRole('button', { name: 'Save & Continue' }).click();
  await page.locator('#group_info').click();
  await page.locator('#group_info').fill('This field is for "Group Info"');
  await page.getByPlaceholder('Adults').click();
  await page.getByPlaceholder('Adults').fill('3');
  await page.getByPlaceholder('Children').click();
  await page.getByPlaceholder('Children').fill('3');
  await page.getByLabel('-30').check();
  await page.getByLabel('-45').check();
  await page.getByLabel('-65').check();
  await page.getByLabel('0-').check();
  await page.getByLabel('4-').check();
  await page.getByLabel('-12').check();
  await page.locator('#member1_first_name').click();
  await page.locator('#member1_first_name').fill('FakeAdult2');
  await page.locator('#member1_last_name').click();
  await page.locator('#member1_last_name').fill('Visitor' + num);
  await page.locator('#member1_email').click();
  await page.locator('#member1_email').fill('BigAppleTesting2312+visitor'+ num + '@gmail.com');
  await page.locator('#member2_first_name').click();
  await page.locator('#member2_first_name').fill('FakeAdult3');
  await page.locator('#member2_last_name').click();
  await page.locator('#member2_last_name').fill('Visitor'+num);
  await page.locator('#member2_email').click();
  await page.locator('#member2_email').fill('BigAppleTesting2312+visitor' + num + '@gmail.com');
  await page.getByRole('button', { name: 'Save & Continue' }).click();
  await page.locator('#arrival_date').click();
  await page.getByRole('cell', { name: '»' }).click();
  await page.getByRole('cell', { name: '10' }).click();
  await page.locator('#departure_date').click();
  await page.getByRole('cell', { name: '20' }).nth(1).click();
  await page.getByPlaceholder('1st Choice').click();
  await page.getByRole('cell', { name: '11' }).click();
  await page.getByPlaceholder('2nd Choice').click();
  await page.getByRole('cell', { name: '12' }).click();
  await page.getByPlaceholder('3rd Choice').click();
  await page.getByRole('cell', { name: '13' }).click();
  await page.locator('#date_notes').click();
  await page.locator('#date_notes').fill('This field is for "Date Notes"');
  await page.getByRole('button', { name: 'Save & Continue' }).click();
  await page.locator('#accommodation_hotel_name').click();
  await page.locator('#accommodation_hotel_name').fill('Fake Hotel Name');
  await page.locator('#accommodation_hotel_city').click();
  await page.locator('#accommodation_hotel_city').fill('Fake Hotel Address 1');
  await page.locator('#accommodation_hotel_address').click();
  await page.locator('#accommodation_hotel_address').fill('Fake Hotel Address 2');
  await page.locator('#accommodation_hotel_phone').click();
  await page.locator('#accommodation_hotel_phone').fill('4');
  await page.locator('#accommodation_hotel_reservation_name').click();
  await page.locator('#accommodation_hotel_reservation_name').fill('Fake Name On Reservation');
  await page.getByRole('textbox', { name: 'Phone' }).click();
  await page.getByRole('textbox', { name: 'Phone' }).fill('5');
  await page.locator('select[name="accommodation_phone_type"]').selectOption('Mobile');
  await page.getByRole('button', { name: 'Save & Continue' }).click();
  await page.locator('#neighborhood_1').selectOption('3');
  await page.locator('#neighborhood_2').selectOption('4');
  await page.locator('#neighborhood_3').selectOption('1');
  await page.locator('#other_neighbourhoods').click();
  await page.locator('#other_neighbourhoods').fill('This field is for "Other Neighborhood"');
  await page.locator('#interest_1').selectOption('2');
  await page.locator('#interest_2').selectOption('3');
  await page.locator('#special_occasion').selectOption('1');
  await page.locator('#other_interests').click();
  await page.locator('#other_interests').fill('This field is for "Other Interests"');
  await page.getByRole('button', { name: 'Save & Continue' }).click();
  await page.getByRole('button', { name: 'Save & Continue' }).click();
  await page.getByText('Yes').nth(1).click();
  await page.locator('#accessibility_needs_notes').click();
  await page.locator('#accessibility_needs_notes').fill('This field is for "Reasonable Accommodations"');
  await page.getByLabel('If we receive a media request').check();
  await page.locator('#referred_from').selectOption('Internet');
  await page.locator('#referred_from_other').click();
  await page.locator('#referred_from_other').fill('This field is for "Other(more detail)"');
  await page.locator('#visit_notes').click();
  await page.locator('#visit_notes').fill('This field is for "Is there anything else you would like to let us know about your visit"');
  await page.getByRole('button', { name: 'Submit' }).click();
  await expect(page.getByRole('main')).toContainText('An email has been sent. Please check your email inbox and verify your account.');
  await expect(page.getByRole('heading')).toContainText('Thank You !!');
});